version: '3'
services:
  solr:
    image: solr:7.4.0
    ports:
     - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - ./docker/solr.in.sh:/opt/solr/bin/solr.in.sh
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - dataSheet
    networks:
      - backend
  
  logdb:
    image: mariadb:10.3.9
    expose:
      - 3306
    ports:
     - "3306:3306"
    restart: always
    env_file:
      - logdb.env
    volumes:
      - logdb_data:/var/lib/mysql
    networks: 
      - backend

  mss-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - solr
    volumes:
      - ./hazard-ds/hazard-dataset:/hazard-ds/hazard-dataset:ro
    networks: 
      - backend

  test:
    image: debian
    depends_on:
      - solr
    volumes:
      - ./hazard-ds/hazard-dataset:/hazard-ds/hazard-dataset:ro
      - ./hazard-ds/fscMap.txt:/hazard-ds/fscMap.txt
      - ./hazard-ds/fsgMap.txt:/hazard-ds/fsgMap.txt
    tty: true
    networks:
      - backend

  mss-client:
    build: ./frontend/
    environment: 
      - API_BASE_URL=http://localhost:8080
    ports:
      - "80:80"

volumes:
  solr_data:
  logdb_data:

networks: 
  backend: