version: '3'
services:
  solr:
    image: solr:7.4.0
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
      - ./docker/solr.in.sh:/opt/solr/bin/solr.in.sh
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - dataSheet
    networks:
      - backend

  mss-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - solr
    volumes:
      - ./hazard-dataset:/hazard-dataset:ro
    networks: 
      - backend

  test:
    image: debian
    depends_on:
      - solr
    tty: true
    networks:
      - backend

  mss-client:
    build: ./frontend/
    environment: 
      - API_BASE_URL=http://localhost:8080
    ports:
      - "80:80"

volumes:
  data:

networks: 
  backend: