version: '3'
services:
  solr:
    image: solr:7.4.0
    restart: always
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
      - {{ mss_path }}/docker/solr.in.sh:/opt/solr/bin/solr.in.sh
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - dataSheet
    networks:
      - backend

  logdb:
    image: mariadb:10.3.9
    restart: always
    env_file:
      - logdb.env
    volumes:
      - logdb_data:/var/lib/mysql
    networks: 
      - backend

  mss-server:
    image: materialsafetysearch/private:backend-next
    restart: always
    depends_on:
      - solr
    environment:
      - VIRTUAL_HOST=${SERVER_DOMAIN}
      - VIRTUAL_NETWORK=${NETWORK}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${SERVER_DOMAIN}
      - LETSENCRYPT_EMAIL=webmaster@leoek.tech
    volumes:
      - {{ mss_path }}/hazard-ds/hazard-dataset:/hazard-ds/hazard-dataset:ro
    networks:
      - backend
      - proxy-tier

  mss-client:
    image: materialsafetysearch/private:frontend-next
    restart: always
    environment:
      - API_BASE_URL=https://${SERVER_DOMAIN}
      - VIRTUAL_HOST=${CLIENT_DOMAIN}
      - VIRTUAL_NETWORK=${NETWORK}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${CLIENT_DOMAIN}
      - LETSENCRYPT_EMAIL=webmaster@leoek.tech
    networks:
      - proxy-tier

volumes:
  solr_data:
  logdb_data:

networks:
  backend:
  proxy-tier:
    external:
      name: ${NETWORK}