version: '3'
services:

  mss-client:
    image: materialsafetysearch/private:frontend-next
    environment:
      - API_BASE_URL=https://${SERVER_DOMAIN}
      - VIRTUAL_HOST=${CLIENT_DOMAIN}
      - VIRTUAL_NETWORK=${NETWORK}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${CLIENT_DOMAIN}
      - LETSENCRYPT_EMAIL=webmaster@leoek.tech
    networks:
      - proxy-tier

volumes:
  solr_data:
  logdb_data:

networks:
  backend:
  proxy-tier:
    external:
      name: ${NETWORK}